export const FINAL_REDIRECT_ALIASES: Record<string, string> = {
    "''Empire_Ascendant''": 'Empire Ascendant',
    "''Empire Ascendant''": 'Empire Ascendant',
    'ADF-5000': 'ADF-5000 Class Cruiser',
    'Adin_Band': 'Hyperspace#Adin Band',
    'Adin Band': 'Hyperspace#Adin Band',
    'AI': 'Artificial Intelligence',
    'Albanis': 'Albanus',
    'Alliance_Defense_Force': 'Military of the United Earth Alliance',
    'Alliance Defense Force': 'Military of the United Earth Alliance',
    'Alliance_of_Planets_Defense_Force': 'Military of the United Earth Alliance',
    'Alliance of Planets Defense Force': 'Military of the United Earth Alliance',
    'Alliance_of_Planets_Grand_Charter': 'Alliance of Planets Great Charter',
    'Alliance of Planets Grand Charter': 'Alliance of Planets Great Charter',
    'Alpha_Centauri': 'Alpha Centauri System',
    'Alpha Centauri': 'Alpha Centauri System',
    'Amelia_Black': 'Luna Black',
    'Amelia Black': 'Luna Black',
    'Annexation_of_Alpha_Centauri': 'Annexation of Bethija',
    'Annexation of Alpha Centauri': 'Annexation of Bethija',
    'Ansible': 'Urokon',
    'Anthronoris_Empire': 'Pax Anthronoris',
    'Anthronoris Empire': 'Pax Anthronoris',
    'Apollo': 'Apollo (disambiguation)',
    'April_Fools_Debacle': 'Third Battle of Tethys (Second Exodus War)',
    'April Fools Debacle': 'Third Battle of Tethys (Second Exodus War)',
    'Apöt': 'Apöt Virus',
    'Archadian': 'Ixoarchada',
    'Archadians': 'Ixoarchada',
    'Archer_Armored_Car': 'T-88 Armored Combat Vehicle - "Archer"',
    'Archer Armored Car': 'T-88 Armored Combat Vehicle - "Archer"',
    'Auellal_Class_Variable_Cruiser': 'Auellal Class Variable Warship',
    'Auellal Class Variable Cruiser': 'Auellal Class Variable Warship',
    'Autocannon': 'Terran Autocannon',
    'Autocannons': 'Terran Autocannon',
    'Battle_of_Titanian_12': 'Second Battle of Cronus',
    'Battle of Titanian 12': 'Second Battle of Cronus',
    'Benjamin_Parman': 'Ben Parman',
    'Benjamin Parman': 'Ben Parman',
    'Ben_Parman': 'Walter Benjamin-Parman von Muench',
    'Ben Parman': 'Walter Benjamin-Parman von Muench',
    'Berlusconi': 'Berlusconi (disambiguation)',
    'Blackis_Civil_War': 'Imperial Civil War',
    'Blackis Civil War': 'Imperial Civil War',
    'Black_Armada_of_the_Royal_Imperail_Navy': 'Black Armada of the Royal Imperial Navy',
    'Black Armada of the Royal Imperail Navy': 'Black Armada of the Royal Imperial Navy',
    'Blaster': 'Bukrah Energy Weapon',
    'Blazton_Heavy_Industries': 'Blasius állam-Nehézipar',
    'Blazton Heavy Industries': 'Blasius állam-Nehézipar',
    'Blazton_Industries': 'Blasius állam-Nehézipar',
    'Blazton Industries': 'Blasius állam-Nehézipar',
    'Blazton_Territorial_Air_Forces': 'Blasius Territorial Air Forces',
    'Blazton Territorial Air Forces': 'Blasius Territorial Air Forces',
    'Bukrah': 'Bukrah Energy Weapon',
    'Cecil_Au-Yeung': 'Cecil Au-Yueng',
    'Cecil Au-Yeung': 'Cecil Au-Yueng',
    'CG-1_Omaha': 'FDS Omaha',
    'CG-1 Omaha': 'FDS Omaha',
    'CG-2_Drake': 'FDS Drake',
    'CG-2 Drake': 'FDS Drake',
    'CG-3_Imposis': 'FDS Imposis',
    'CG-3 Imposis': 'FDS Imposis',
    'China_(Terra)': "People's Republic of China (Terra)",
    'China (Terra)': "People's Republic of China (Terra)",
    'Christopher_Dayton': 'Chris Dayton',
    'Christopher Dayton': 'Chris Dayton',
    'CIA': 'United Earth Alliance Central Intelligence Agency',
    'Civil_Motors': 'Civil Motor Company',
    'Civil Motors': 'Civil Motor Company',
    'Clans_of_the_Mesarthrim': 'Clans of the Mesarthrim',
    'Clans of the Mesarthrim': 'Clans of the Mesarthrim',
    'Clan_Lords': 'Clan Lord',
    'Clan Lords': 'Clan Lord',
    'Coilgun': 'Meroniri Coilgun',
    'Communist': 'Communism',
    'Communists': 'Communism',
    'Communist_Party': 'Communism',
    'Communist Party': 'Communism',
    'Constitution_of_the_Federated_Districts_of_the_Prefecture': 'Federated Districts of the Prefecture Constitution',
    'Constitution of the Federated Districts of the Prefecture': 'Federated Districts of the Prefecture Constitution',
    "Culture_of_Krlbila_Jitu'nge": "Culture of Kabila Jitu'nge",
    "Culture of Krlbila Jitu'nge": "Culture of Kabila Jitu'nge",
    'Culture_of_the_Reigess_Sovereignty': 'Culture of the Reigess Suverände',
    'Culture of the Reigess Sovereignty': 'Culture of the Reigess Suverände',
    'Culture_of_the_Terran_Embassy': 'Culture of the Sol System Authority',
    'Culture of the Terran Embassy': 'Culture of the Sol System Authority',
    'Darel_Fusala': 'Naimen Ladosen',
    'Darel Fusala': 'Naimen Ladosen',
    'Dawn_Emperor': 'Mircan Prekohr',
    'Dawn Emperor': 'Mircan Prekohr',
    "Demographics_of_Krlbila_Jitu'nge": "Demographics of Kabila Jitu'nge",
    "Demographics of Krlbila Jitu'nge": "Demographics of Kabila Jitu'nge",
    'Desyat_Band': 'Hyperspace#Desyat Band',
    'Desyat Band': 'Hyperspace#Desyat Band',
    'Dollars': 'Dollar',
    'Dva_Band': 'Hyperspace#Dva Band',
    'Dva Band': 'Hyperspace#Dva Band',
    'EI': 'Engineered Intelligence',
    'Eituk': 'K-6 Eituk',
    'Empire': 'Onyx Empire',
    'Entropy_Drives': 'Entropy Drive',
    'Entropy Drives': 'Entropy Drive',
    'F-12_Vampire': 'F-12 Superiority Fighter - "Vampire"',
    'F-12 Vampire': 'F-12 Superiority Fighter - "Vampire"',
    'F-16_Piranha': 'F-16 Superiority Fighter - "Piranha"',
    'F-16 Piranha': 'F-16 Superiority Fighter - "Piranha"',
    'F-4': 'F-4 (disambiguation)',
    'F-4_Raven': 'F-04 Superiority Fighter - "Raven"',
    'F-4 Raven': 'F-04 Superiority Fighter - "Raven"',
    'F-4_Ravens': 'F-04 Superiority Fighter - "Raven"',
    'F-4 Ravens': 'F-04 Superiority Fighter - "Raven"',
    'F-9E_Valkyrie': 'F-09 Carrier Fighter - "Valkyrie"',
    'F-9E Valkyrie': 'F-09 Carrier Fighter - "Valkyrie"',
    'F-9_Valkyrie': 'F-09 Carrier Fighter - "Valkyrie"',
    'F-9 Valkyrie': 'F-09 Carrier Fighter - "Valkyrie"',
    'Forces_Clash_Around_Tethys': 'First Battle of Tethys',
    'Forces Clash Around Tethys': 'First Battle of Tethys',
    'Gauss_Cannons': 'Terran Gauss Cannon',
    'Gauss Cannons': 'Terran Gauss Cannon',
    'GDP': 'Gross Domestic Product',
    'Geckan': 'Gorhamut',
    'Geckans': 'Gorhamut',
    'Government_of_the_Terran_Embassy': 'Government of the Sol System Authority',
    'Government of the Terran Embassy': 'Government of the Sol System Authority',
    'Grand_Admiral': 'Grand Admiral (disambiguation)',
    'Grand Admiral': 'Grand Admiral (disambiguation)',
    'Gregor_Blazton': 'Blasius Gregöri János',
    'Gregor Blazton': 'Blasius Gregöri János',
    'Habitat': 'Void World',
    'History_of_Lorithan': 'History of Rikaz o Fii Huern iv Lorithan',
    'History of Lorithan': 'History of Rikaz o Fii Huern iv Lorithan',
    'HMS_Bahari_Shela': 'The Bahari Shela',
    'HMS Bahari Shela': 'The Bahari Shela',
    'Huern': 'Hamur Hauren',
    'Human': 'Humans',
    'Hyperspace_limit_432': 'Hyperspace Limit',
    'Hyperspace limit 432': 'Hyperspace Limit',
    'Icronian_Consortium': 'Ikronin Jurekön',
    'Icronian Consortium': 'Ikronin Jurekön',
    'Icronian_Conventional_Missile_Warheads': 'Conventional Missile Warheads - Ikronin',
    'Icronian Conventional Missile Warheads': 'Conventional Missile Warheads - Ikronin',
    'Icronian_Repulsor_Cannon': 'Repulsor Cannon',
    'Icronian Repulsor Cannon': 'Repulsor Cannon',
    'Icronian_Repulsor_Shield_Field_Generator': 'Repulsor Shield Field Generator',
    'Icronian Repulsor Shield Field Generator': 'Repulsor Shield Field Generator',
    'Ikronin_Jurekon': 'Ikronin Jurekön',
    'Ikronin Jurekon': 'Ikronin Jurekön',
    'Imperial_Civil_War': 'Torimur Civil War',
    'Imperial Civil War': 'Torimur Civil War',
    'Imperial_Credits': 'Imperial Credit',
    'Imperial Credits': 'Imperial Credit',
    'Imperial_Military': 'Military of the Onyx Empire',
    'Imperial Military': 'Military of the Onyx Empire',
    'Intelligence_of_the_Empire': 'Intelligence of the Onyx Empire',
    'Intelligence of the Empire': 'Intelligence of the Onyx Empire',
    'Invasion_of_Earth': 'First Invasion of Sol',
    'Invasion of Earth': 'First Invasion of Sol',
    'Ipsof': 'Ipsoff',
    'Iridi': 'Ixoarchada Iridi',
    'Isreal_(Terra)': 'Israel (Terra)',
    'Isreal (Terra)': 'Israel (Terra)',
    'Iterin_Corahl_Deseraht': 'Intelligence of Rikaz o Fii Huern iv Lorithan',
    'Iterin Corahl Deseraht': 'Intelligence of Rikaz o Fii Huern iv Lorithan',
    'Jeff_Nolan': 'Geoffrey Nolan-Marshall',
    'Jeff Nolan': 'Geoffrey Nolan-Marshall',
    'Jerome_Black_(BG-1)': 'BG-1 Jerome Black',
    'Jerome Black (BG-1)': 'BG-1 Jerome Black',
    'Jiliur_Raegos': 'Jiliur Beskolyda nav Raegos',
    'Jiliur Raegos': 'Jiliur Beskolyda nav Raegos',
    'Josh_Carter': 'Joshua Cartör von Fuerst',
    'Josh Carter': 'Joshua Cartör von Fuerst',
    'Josiah_Hlow': 'Josiah MacArthur Hlow',
    'Josiah Hlow': 'Josiah MacArthur Hlow',
    'Jupiter_Motors': 'Jupiter Motor Company',
    'Jupiter Motors': 'Jupiter Motor Company',
    'Kabila_Duka': "Kabila iku Gol'nde",
    'Kabila Duka': "Kabila iku Gol'nde",
    'KPA': 'Kalidasa Planetary Authority',
    'Krenschov_Effect': 'Hyperspace',
    'Krenschov Effect': 'Hyperspace',
    'Krlbila_Grlnudr': "Kabila iku Gol'nde",
    'Krlbila Grlnudr': "Kabila iku Gol'nde",
    "Krlbila_Jitu'nge": "Kabila Jitu'nge",
    "Krlbila Jitu'nge": "Kabila Jitu'nge",
    'Ks-1_Pegasus': 'Pegasus Dropship',
    'Ks-1 Pegasus': 'Pegasus Dropship',
    'Laojiu_District': 'Territory of the Federated Districts of the Prefecture#Laojiu District',
    'Laojiu District': 'Territory of the Federated Districts of the Prefecture#Laojiu District',
    'Lorithos_Bukrah_Energy_Weapon': 'Bukrah Energy Weapon',
    'Lorithos Bukrah Energy Weapon': 'Bukrah Energy Weapon',
    'Lyrae_Incursion': 'First Invasion of Lyrae',
    'Lyrae Incursion': 'First Invasion of Lyrae',
    'M-11a_Field_Gun': 'M-13 Field Gun',
    'M-11a Field Gun': 'M-13 Field Gun',
    'M-15_Crew-Portable_60mm_Mortar': 'M-15 Crew-Portable Mortar (60mm)',
    'M-15 Crew-Portable 60mm Mortar': 'M-15 Crew-Portable Mortar (60mm)',
    'M-16_Powered_Armor': 'M-16 Power-Assisted Heavy Armor - "Excalibur"',
    'M-16 Powered Armor': 'M-16 Power-Assisted Heavy Armor - "Excalibur"',
    'M-17_Utility_Truck': 'M-39 Utility Truck',
    'M-17 Utility Truck': 'M-39 Utility Truck',
    'M-18_Apollo': 'M-24 Medium Combat Rig Chassis - "Apollo"',
    'M-18 Apollo': 'M-24 Medium Combat Rig Chassis - "Apollo"',
    'M-19_Powered_Armor': 'M-16 Power-Assisted Heavy Armor - "Excalibur"',
    'M-19 Powered Armor': 'M-16 Power-Assisted Heavy Armor - "Excalibur"',
    'M-1_Field_Combat_Uniform': 'M-01 Field Combat Uniform',
    'M-1 Field Combat Uniform': 'M-01 Field Combat Uniform',
    'M-20_Grendel': 'M-17 Mobile Exoskeletal Armor - "Grendel"',
    'M-20 Grendel': 'M-17 Mobile Exoskeletal Armor - "Grendel"',
    "M-22a_Light_Beam_Weapon_-_''Toaster''": 'M-23 Light Beam Weapon - "Toaster"',
    "M-22a Light Beam Weapon - ''Toaster''": 'M-23 Light Beam Weapon - "Toaster"',
    "M-22a_Light_Neutron_Beam_Weapon_-_''Toaster''": 'M-23 Light Beam Weapon - "Toaster"',
    "M-22a Light Neutron Beam Weapon - ''Toaster''": 'M-23 Light Beam Weapon - "Toaster"',
    'M-22_Bradshaw': 'M-25 Medium Support Rig Chassis - "Bradshaw"',
    'M-22 Bradshaw': 'M-25 Medium Support Rig Chassis - "Bradshaw"',
    "M-22_Light_Autocannon_-_''Thumper''": 'M-22 Light Autocannon - "Stinger"',
    "M-22 Light Autocannon - ''Thumper''": 'M-22 Light Autocannon - "Stinger"',
    "M-24a_Medium_Support_Rig_Chassis_-_''Bradshaw''": 'M-25 Medium Support Rig Chassis - "Bradshaw"',
    "M-24a Medium Support Rig Chassis - ''Bradshaw''": 'M-25 Medium Support Rig Chassis - "Bradshaw"',
    "M-24_Medium_Rig_Chassis_-_''Apollo''": 'M-24 Medium Combat Rig Chassis - "Apollo"',
    "M-24 Medium Rig Chassis - ''Apollo''": 'M-24 Medium Combat Rig Chassis - "Apollo"',
    'M-24_Towed_155mm_Artillery_Cannon': 'M-40 Towed Artillery Cannon (155mm)',
    'M-24 Towed 155mm Artillery Cannon': 'M-40 Towed Artillery Cannon (155mm)',
    'M-25_Grenade_Launcher': 'M-12 Grenade Launcher',
    'M-25 Grenade Launcher': 'M-12 Grenade Launcher',
    'M-25_Rig-Portable_Mortar_(120mm)': 'M-26 Rig-Portable Mortar (120mm)',
    'M-25 Rig-Portable Mortar (120mm)': 'M-26 Rig-Portable Mortar (120mm)',
    'M-26_Electric_Control_Weapon': 'M-27 Electric Control Weapon',
    'M-26 Electric Control Weapon': 'M-27 Electric Control Weapon',
    'M-27_Medium_Combat_Vehicle_Chassis': 'M-28 Medium Combat Vehicle Chassis - "Enforcer"',
    'M-27 Medium Combat Vehicle Chassis': 'M-28 Medium Combat Vehicle Chassis - "Enforcer"',
    "M-27_Medium_Combat_Vehicle_Chassis_-_''Enforcer''": 'M-28 Medium Combat Vehicle Chassis - "Enforcer"',
    "M-27 Medium Combat Vehicle Chassis - ''Enforcer''": 'M-28 Medium Combat Vehicle Chassis - "Enforcer"',
    'M-27_Shotgun': 'M-10 Shotgun',
    'M-27 Shotgun': 'M-10 Shotgun',
    'M-28a_HE_Grenade': 'M-08a HE Grenade',
    'M-28a HE Grenade': 'M-08a HE Grenade',
    "M-28a_Medium_Neutron_Beam_Weapon_-_''Scorcher''": 'M-30 Medium Neutron Beam Weapon - "Scorcher"',
    "M-28a Medium Neutron Beam Weapon - ''Scorcher''": 'M-30 Medium Neutron Beam Weapon - "Scorcher"',
    'M-28b_Smoke_Grenade': 'M-08b Smoke Grenade',
    'M-28b Smoke Grenade': 'M-08b Smoke Grenade',
    'M-28c_Napalm_Grenade': 'M-08c Napalm Grenade',
    'M-28c Napalm Grenade': 'M-08c Napalm Grenade',
    'M-28d_Flash-Bang_Grenade': 'M-08d Flash-Bang Grenade',
    'M-28d Flash-Bang Grenade': 'M-08d Flash-Bang Grenade',
    'M-28e_Firebomb_Grenade': 'M-08e Firebomb Grenade',
    'M-28e Firebomb Grenade': 'M-08e Firebomb Grenade',
    'M-28_Fragmentation_Grenade': 'M-08 Fragmentation Grenade',
    'M-28 Fragmentation Grenade': 'M-08 Fragmentation Grenade',
    "M-28_Medium_Autocannon_-_''Thumper''": 'M-29 Medium Autocannon - "Thumper"',
    "M-28 Medium Autocannon - ''Thumper''": 'M-29 Medium Autocannon - "Thumper"',
    "M-29a_Heavy_Support_Rig_Chassis_-_''Zeus''": 'M-32 Heavy Support Rig Chassis - "Zeus"',
    "M-29a Heavy Support Rig Chassis - ''Zeus''": 'M-32 Heavy Support Rig Chassis - "Zeus"',
    'M-29_60mm_Mortar': 'M-15 Crew-Portable Mortar (60mm)',
    'M-29 60mm Mortar': 'M-15 Crew-Portable Mortar (60mm)',
    "M-29_Heavy_Combat_Rig_Chassis_-_''Hades''": 'M-31 Heavy Combat Rig Chassis - "Hades"',
    "M-29 Heavy Combat Rig Chassis - ''Hades''": 'M-31 Heavy Combat Rig Chassis - "Hades"',
    'M-2A_Armadillo': 'M-38 Armored Personnel Carrier - "Armadillo"',
    'M-2A Armadillo': 'M-38 Armored Personnel Carrier - "Armadillo"',
    'M-2_Armadillo': 'M-38 Armored Personnel Carrier - "Armadillo"',
    'M-2 Armadillo': 'M-38 Armored Personnel Carrier - "Armadillo"',
    'M-30_80mm_Mortar': 'M-19 Exoskeletal-Portable Mortar (81mm)',
    'M-30 80mm Mortar': 'M-19 Exoskeletal-Portable Mortar (81mm)',
    'M-30_81mm_Mortar': 'M-19 Exoskeletal-Portable Mortar (81mm)',
    'M-30 81mm Mortar': 'M-19 Exoskeletal-Portable Mortar (81mm)',
    'M-30_Heavy_Anti-Armor_Weapon': 'M-33 Heavy Anti-Armor Weapon',
    'M-30 Heavy Anti-Armor Weapon': 'M-33 Heavy Anti-Armor Weapon',
    "M-31a_Heavy_Neutron_Beam_Weapon_-_''Incinerator''": 'M-35 Heavy Neutron Beam Weapon - "Incinerator"',
    "M-31a Heavy Neutron Beam Weapon - ''Incinerator''": 'M-35 Heavy Neutron Beam Weapon - "Incinerator"',
    'M-31_120mm_Mortar': 'M-26 Rig-Portable Mortar (120mm)',
    'M-31 120mm Mortar': 'M-26 Rig-Portable Mortar (120mm)',
    "M-31_Heavy_Autocannon_-_''Earthquake''": 'M-34 Heavy Autocannon - "Earthquake"',
    "M-31 Heavy Autocannon - ''Earthquake''": 'M-34 Heavy Autocannon - "Earthquake"',
    "M-32_All-Terrain_Vehicle_-_''Badger''": 'M-36 All-Terrain Vehicle - "Badger"',
    "M-32 All-Terrain Vehicle - ''Badger''": 'M-36 All-Terrain Vehicle - "Badger"',
    "M-32_All-Terrain_Vehicle_-_''Bobcat''": 'M-36 All-Terrain Vehicle - "Badger"',
    "M-32 All-Terrain Vehicle - ''Bobcat''": 'M-36 All-Terrain Vehicle - "Badger"',
    "M-33_Armored_Personnel_Carrier_-_''Armadillo''": 'M-38 Armored Personnel Carrier - "Armadillo"',
    "M-33 Armored Personnel Carrier - ''Armadillo''": 'M-38 Armored Personnel Carrier - "Armadillo"',
    "M-33_Infantry_Fighting_Vehicle_-_''Goblin''": 'M-37 Infantry Fighting Vehicle - "Goblin"',
    "M-33 Infantry Fighting Vehicle - ''Goblin''": 'M-37 Infantry Fighting Vehicle - "Goblin"',
    "M-34_Armored_Personnel_Carrier_-_''Armadillo''": 'M-38 Armored Personnel Carrier - "Armadillo"',
    "M-34 Armored Personnel Carrier - ''Armadillo''": 'M-38 Armored Personnel Carrier - "Armadillo"',
    'M-35_Utility_Truck': 'M-39 Utility Truck',
    'M-35 Utility Truck': 'M-39 Utility Truck',
    'M-36_Towed_Artillery_Cannon_(155mm)': 'M-40 Towed Artillery Cannon (155mm)',
    'M-36 Towed Artillery Cannon (155mm)': 'M-40 Towed Artillery Cannon (155mm)',
    "M-37_Main_Battle_Tank_Chassis_-_''Dragon''": 'M-41 Main Battle Tank Chassis - "Dragon"',
    "M-37 Main Battle Tank Chassis - ''Dragon''": 'M-41 Main Battle Tank Chassis - "Dragon"',
    "M-38_Heavy_Combat_Vehicle_Chassis_-_''Warlord''": 'M-42 Heavy Combat Vehicle Chassis - "Warlord"',
    "M-38 Heavy Combat Vehicle Chassis - ''Warlord''": 'M-42 Heavy Combat Vehicle Chassis - "Warlord"',
    'M-5_Hercules': 'M-21 Light Combat Rig Chassis - "Hercules"',
    'M-5 Hercules': 'M-21 Light Combat Rig Chassis - "Hercules"',
    'M-6a_Combat_Knife': 'M-04 Combat Knife',
    'M-6a Combat Knife': 'M-04 Combat Knife',
    'M-6b_Pistol': 'M-05 Pistol',
    'M-6b Pistol': 'M-05 Pistol',
    'M-6_Selectable_Assault_Battle_Rifle_(SABR)': 'M-06 Selectable Assault Battle Rifle (SABR)',
    'M-6 Selectable Assault Battle Rifle (SABR)': 'M-06 Selectable Assault Battle Rifle (SABR)',
    'M-7_Zeus': 'M-32 Heavy Support Rig Chassis - "Zeus"',
    'M-7 Zeus': 'M-32 Heavy Support Rig Chassis - "Zeus"',
    'M-9a_Medium_Anti-Armor_Weapon': 'M-18 Medium Anti-Armor Weapon',
    'M-9a Medium Anti-Armor Weapon': 'M-18 Medium Anti-Armor Weapon',
    'M-9_Light_Anti-Armor_Weapon': 'M-09 Light Anti-Armor Weapon',
    'M-9 Light Anti-Armor Weapon': 'M-09 Light Anti-Armor Weapon',
    'M-XXUtility_Truck': 'M-39 Utility Truck',
    'M-XXUtility Truck': 'M-39 Utility Truck',
    'M-XX_Armadillo': 'M-38 Armored Personnel Carrier - "Armadillo"',
    'M-XX Armadillo': 'M-38 Armored Personnel Carrier - "Armadillo"',
    'M-XX_Towed_155mm_Artillery_Cannon': 'M-40 Towed Artillery Cannon (155mm)',
    'M-XX Towed 155mm Artillery Cannon': 'M-40 Towed Artillery Cannon (155mm)',
    'Magnetic_Accelerator_Cannon': 'Terran Mass Drivers',
    'Magnetic Accelerator Cannon': 'Terran Mass Drivers',
    'Marcolitiae_Ramius': 'Mircas Rasune',
    'Marcolitiae Ramius': 'Mircas Rasune',
    'Me-32_Patton': 'Me-32 Superiority Fighter - "Sturmfaust"',
    'Me-32 Patton': 'Me-32 Superiority Fighter - "Sturmfaust"',
    'Meroniri_Mass-to-Energy_Conversion_Bomb': 'Mass-to-Energy Conversion Bomb',
    'Meroniri Mass-to-Energy Conversion Bomb': 'Mass-to-Energy Conversion Bomb',
    'Meroniri_Yatisu': 'Military of the Meroniri Terinasi',
    'Meroniri Yatisu': 'Military of the Meroniri Terinasi',
    'Mesarnak_Overseers': 'Overseer Administration of the Mesarthrim Clans',
    'Mesarnak Overseers': 'Overseer Administration of the Mesarthrim Clans',
    'Mesarthrim_Resistance': 'Mesarthrim Rebellion',
    'Mesarthrim Resistance': 'Mesarthrim Rebellion',
    'Mestharim_Mark': 'Mesarthrim Mark',
    'Mestharim Mark': 'Mesarthrim Mark',
    'Military_of_the_Terran_Embassy': 'Military of the Sol System Authority',
    'Military of the Terran Embassy': 'Military of the Sol System Authority',
    'Mircas_Rasium': 'Mircas Rasune',
    'Mircas Rasium': 'Mircas Rasune',
    'Mourning': 'Mourning - by Seth Dickinson',
    'Mysterium-Stahl': 'Mystery Steel',
    'Nathaniel_Hinks_von_Stadt': 'Nathaniel Hinks',
    'Nathaniel Hinks von Stadt': 'Nathaniel Hinks',
    'Nathan_Hinks': 'Nathaniel Hinks',
    'Nathan Hinks': 'Nathaniel Hinks',
    'Netherlands': 'Netherlands (Terra)',
    'New_Albany': 'Albanus',
    'New Albany': 'Albanus',
    'NGV_Guiseppe_Garibaldi': 'NGV Giuseppe Garibaldi',
    'NGV Guiseppe Garibaldi': 'NGV Giuseppe Garibaldi',
    'Nic_Piazzaro': 'Nicodemo Guadalupe Piazzaro',
    'Nic Piazzaro': 'Nicodemo Guadalupe Piazzaro',
    'Nimitz_class_Gunship_3383': 'Nimitz Class Gunship',
    'Nimitz class Gunship 3383': 'Nimitz Class Gunship',
    'Ollivians_Crossing': "Ollivian's Crossing",
    'Ollivians Crossing': "Ollivian's Crossing",
    'Ologrian': 'Ngrligru',
    'Ologrians': 'Ngrligru',
    'Ologrian_Kabila_Duka': "Kabila iku Gol'nde",
    'Ologrian Kabila Duka': "Kabila iku Gol'nde",
    'Ologrian_Kigao_Proton-Bond_Armor': 'Ngrligru Kigao Proton-Bond Armor',
    'Ologrian Kigao Proton-Bond Armor': 'Ngrligru Kigao Proton-Bond Armor',
    "Ologrian_Mkuki'kali_Energy_Lance": "Mkuki'kali Energy Lance",
    "Ologrian Mkuki'kali Energy Lance": "Mkuki'kali Energy Lance",
    'Orion_(spacecraft)': 'Orion Spacecraft',
    'Orion (spacecraft)': 'Orion Spacecraft',
    'Oritar_Class_Freighter': 'Oritar Class Patrol Ship',
    'Oritar Class Freighter': 'Oritar Class Patrol Ship',
    'Oronus': 'Oronus System',
    'Peculiums': 'Peculium',
    "People's_Republic_of_China": "People's Republic of China (Terra)",
    "People's Republic of China": "People's Republic of China (Terra)",
    'Praetoria_Class': 'Praetoria Class Heavy Combatant',
    'Praetoria Class': 'Praetoria Class Heavy Combatant',
    'Prefecture': 'Federated Districts of the Prefecture',
    'Prefecture_Air_Force': 'Federated Districts Air Force',
    'Prefecture Air Force': 'Federated Districts Air Force',
    'Prefecture_Army': 'Prefecture Legion Corps',
    'Prefecture Army': 'Prefecture Legion Corps',
    'Prefecture_Military_Dress_Uniform': 'M-02 Formal Dress Uniform',
    'Prefecture Military Dress Uniform': 'M-02 Formal Dress Uniform',
    'Prefecture_Military_Field_Combat_Uniform': 'M-01 Field Combat Uniform',
    'Prefecture Military Field Combat Uniform': 'M-01 Field Combat Uniform',
    'Prefecture_Navy': 'Prefecture Galactic Navy',
    'Prefecture Navy': 'Prefecture Galactic Navy',
    'Provider_Class_Freighter': 'Provider Class Hauler',
    'Provider Class Freighter': 'Provider Class Hauler',
    'Ptolemy_Sector': 'Njiorin Sector',
    'Ptolemy Sector': 'Njiorin Sector',
    'Pyat_Band': 'Hyperspace#Pyat Band',
    'Pyat Band': 'Hyperspace#Pyat Band',
    'Ranks_in_the_Air_Force': 'Ranks in the Prefecture Air Force',
    'Ranks in the Air Force': 'Ranks in the Prefecture Air Force',
    'Ranks_in_the_Galactic_Navy': 'Ranks in the Prefecture Galactic Navy',
    'Ranks in the Galactic Navy': 'Ranks in the Prefecture Galactic Navy',
    'Ranks_in_the_Legion_Corps': 'Ranks in the Prefecture Legion Corps',
    'Ranks in the Legion Corps': 'Ranks in the Prefecture Legion Corps',
    'Ranks_in_the_Marine_Corps': 'Ranks in the Prefecture Marine Corps',
    'Ranks in the Marine Corps': 'Ranks in the Prefecture Marine Corps',
    'Reigen': 'Reigens',
    'Reigess_Royal_Navy': 'Reigess Renskader',
    'Reigess Royal Navy': 'Reigess Renskader',
    'Reigess_Royal_Territorial_Guard': 'Reigess Mark Vaktida',
    'Reigess Royal Territorial Guard': 'Reigess Mark Vaktida',
    'Reigess_Sovereignty': 'Reigess Suverände',
    'Reigess Sovereignty': 'Reigess Suverände',
    'Reigess_Suverande': 'Reigess Suverände',
    'Reigess Suverande': 'Reigess Suverände',
    'Relativistic_Mass_Driver': 'Terran Mass Drivers',
    'Relativistic Mass Driver': 'Terran Mass Drivers',
    'Relativistic_Mass_Drivers': 'Terran Mass Drivers',
    'Relativistic Mass Drivers': 'Terran Mass Drivers',
    'Remnant': 'The Remnant',
    'Remnant_of_the_Anthronoris': 'The Remnant',
    'Remnant of the Anthronoris': 'The Remnant',
    'Rigs': 'Rigs',
    'Rikaz_Lorithos': 'Rikaz o Fii Huern iv Lorithan',
    'Rikaz Lorithos': 'Rikaz o Fii Huern iv Lorithan',
    'Rikaz_o_fii_Huern_iv_Lorithan_2231': 'Rikaz o Fii Huern iv Lorithan',
    'Rikaz o fii Huern iv Lorithan 2231': 'Rikaz o Fii Huern iv Lorithan',
    'RLI_Adelisk': 'Adelisk Class Corvette',
    'RLI Adelisk': 'Adelisk Class Corvette',
    'Rox_Augustin': 'Rosh Arufin',
    'Rox Augustin': 'Rosh Arufin',
    'Royal_Imperial_Navy_Battle_Star': 'Imperial Battle Star',
    'Royal Imperial Navy Battle Star': 'Imperial Battle Star',
    'Sacking_of_Tejat': 'First Invasion of Theta Algedi',
    'Sacking of Tejat': 'First Invasion of Theta Algedi',
    'Scimitar_Squadron': 'VF-1 Scimitar Squadron',
    'Scimitar Squadron': 'VF-1 Scimitar Squadron',
    'Sem_Band': 'Hyperspace#Sem Band',
    'Sem Band': 'Hyperspace#Sem Band',
    'Shatter_Point_-_by_Seth_Dickenson': 'Shatter Point',
    'Shatter Point - by Seth Dickenson': 'Shatter Point',
    'Shest_Band': 'Hyperspace#Shest Band',
    'Shest Band': 'Hyperspace#Shest Band',
    'Skratta_Masen': 'Skratta Måsen',
    'Skratta Masen': 'Skratta Måsen',
    'Sol': 'Sol System',
    'Soviet_Union': 'Soviet Union (Terra)',
    'Soviet Union': 'Soviet Union (Terra)',
    'Tanis_Ladosen': 'Naimen Ladosen',
    'Tanis Ladosen': 'Naimen Ladosen',
    'Tavou_District': 'Territory of the Federated Districts of the Prefecture#Tavou District',
    'Tavou District': 'Territory of the Federated Districts of the Prefecture#Tavou District',
    'Tavou_Imports': 'Tavou Imports Trading Group',
    'Tavou Imports': 'Tavou Imports Trading Group',
    'Technology': 'Technological Catalogs',
    'Tejat_Cluster': 'Algedi Cluster',
    'Tejat Cluster': 'Algedi Cluster',
    'Tejat_District': 'Territory of the Federated Districts of the Prefecture#Tejat',
    'Tejat District': 'Territory of the Federated Districts of the Prefecture#Tejat',
    'Terra': 'Earth',
    'Terran': 'Terrans',
    'Terran_Embassy': 'Sol System Authority',
    'Terran Embassy': 'Sol System Authority',
    'Terran_Relativistic_Mass_Drivers': 'Terran Mass Drivers',
    'Terran Relativistic Mass Drivers': 'Terran Mass Drivers',
    'Tesseract_Drive': 'Tesseract',
    'Tesseract Drive': 'Tesseract',
    'Thezerops': 'Gorhamut',
    'The_Empire': 'Onyx Empire',
    'The Empire': 'Onyx Empire',
    'Titan': 'Titan System',
    'Tronit_Class_War_Cruiser': 'Tronit Class Warcruiser',
    'Tronit Class War Cruiser': 'Tronit Class Warcruiser',
    'Turpitz_class_Gunship_3384': 'Turpitz Class Gunship',
    'Turpitz class Gunship 3384': 'Turpitz Class Gunship',
    'Twilight_Empress': 'Talire Huern',
    'Twilight Empress': 'Talire Huern',
    'Uber-General': 'Uber-General of the United Mesarthrim Clans',
    'UCS': 'United Centusi States',
    'UEA': 'United Earth Alliance',
    'Ueda_District': 'Territory of the Federated Districts of the Prefecture',
    'Ueda District': 'Territory of the Federated Districts of the Prefecture',
    'UH-6A_Wyandot': 'CH-6A Wyandot',
    'UH-6A Wyandot': 'CH-6A Wyandot',
    'UMC': 'United Mesarthrim Clans',
    'United_Earth_Alliance_Defense_Force': 'Military of the United Earth Alliance',
    'United Earth Alliance Defense Force': 'Military of the United Earth Alliance',
    'Ursa_Sector': 'Tolana Sector',
    'Ursa Sector': 'Tolana Sector',
    'Vadrie': 'O-24 Vadrie',
    'Volucris_Swarms': 'Volucris Swarm',
    'Volucris Swarms': 'Volucris Swarm',
    'Ward_District': 'Territory of the Federated Districts of the Prefecture#Ward District',
    'Ward District': 'Territory of the Federated Districts of the Prefecture#Ward District',
    'White-eyes': 'White Eyes',
    'White_eyes_666': 'White Eyes',
    'White eyes 666': 'White Eyes',
    'Willim': 'Mesar#Willim',
    'Worlds_of_Rikaz_o_Fii_Huern_iv_Lorithan': 'Territory of Rikaz o Fii Huern iv Lorithan',
    'Worlds of Rikaz o Fii Huern iv Lorithan': 'Territory of Rikaz o Fii Huern iv Lorithan',
    'Worlds_of_the_Colonial_Commonwealth': 'Territory of the Colonial Commonwealth',
    'Worlds of the Colonial Commonwealth': 'Territory of the Colonial Commonwealth',
    'Worlds_of_the_Federated_Districts_of_the_Prefecture': 'Territory of the Federated Districts of the Prefecture',
    'Worlds of the Federated Districts of the Prefecture': 'Territory of the Federated Districts of the Prefecture',
    'Worlds_of_the_Onyx_Empire': 'Territory of the Onyx Empire',
    'Worlds of the Onyx Empire': 'Territory of the Onyx Empire',
    'Wormhole': 'Wormholes',
    'Wormhole_Gate': 'Wormholes',
    'Wormhole Gate': 'Wormholes',
    'Wormhole_Gates': 'Wormholes',
    'Wormhole Gates': 'Wormholes',
    'XM-1_(Imperial_Experimental_Chassis)': 'XV-1 (Imperial Experimental Chassis)',
    'XM-1 (Imperial Experimental Chassis)': 'XV-1 (Imperial Experimental Chassis)',
    'Zak_Huern': 'Zaken Huern',
    'Zak Huern': 'Zaken Huern',
    'Zweite_Flotte': 'United Mesarthrim Clans Second Fleet',
    'Zweite Flotte': 'United Mesarthrim Clans Second Fleet'
};
